<a href="https://colab.research.google.com/github/lokeshparab/Python-Notes/blob/main/Python_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Installing and Importing Numpy**
##**What is Numpy?**
* NumPy is a Python library used for working with arrays.
* It also has functions for working in domain of linear algebra, fourier transform, and matrices. 
* NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely
* This library is widely used in Data Science and Statistics 


In [1]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np

#**Creating array from list**

##**numpy.array()**: 
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

In [6]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

##**Support indexing**

In [7]:
print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4])
print(a[5])

1
2
3
4
5
6


In [10]:
print(a[-6])
print(a[-5])
print(a[-4])
print(a[-3])
print(a[-2])
print(a[-1])

1
2
3
4
5
6


##**Support slicing**

In [12]:
print(a[-6:-2])  # print [1 2 3 4]
print(a[-5:-4])  # print [2]
print(a[-4: 0])  # print []
print(a[:3])     # print [1 2 3]
print(a[2:])     # print [3 4 5 6]
print(a[-1:])    # print [6]
print(a[2:4])    # print [3 4]

[1 2 3 4]
[2]
[]
[1 2 3]
[3 4 5 6]
[6]
[3 4]


#**Shape and Size of array**

In [13]:
lst = [1,2,3,4,5,6]
a = np.array(lst)  
print(a.size)
a.shape

6


(6,)

In [15]:
lst = [
        [1,2,3],
        [4,5,6]
       ]

a = np.array(lst)
print(a.size)
a.shape

6


(2, 3)

In [17]:
lst = [
        [1,2],
        [3,4],
        [5,6],
        [7,8]
      ]
      
a = np.array(lst)
print(a.size)
a.shape

8


(4, 2)

#**Reshape**

In [19]:
lst = [1,2,3,4,5,6]
a = np.array(lst)  

##Method 1

In [21]:
a.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
a.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

##Method 2

In [23]:
np.reshape(a,(3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
np.reshape(a,(2,3))

array([[1, 2, 3],
       [4, 5, 6]])

#**Flatten**
Covert Multi-Dimension or 2D array to 1D array 

In [35]:
lst = [
        [1,2],
        [3,4],
        [5,6],
        [7,8]
      ]
      
a1 = np.array(lst)

a1.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
lst = [
        [1,2,3],
        [4,5,6],
        [7,8,9]
       ]

a2 = np.array(lst)

a2.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#Array of Zeros

zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters

* shape : int or tuple of ints
  * Shape of the new array, e.g., ``(2, 3)`` or ``2``.
* dtype : data-type, optional
  * The desired data-type for the array, e.g., `numpy.int8`.  
  * Default is `numpy.float64`.

* order : {'C', 'F'}, optional, default: 'C'
  * Whether to store multi-dimensional data in row-major
  * (C-style) or column-major (Fortran-style) order in memory.
  * **Note: This is helpful while sorting in which manner**

* like : array_like
  * Reference object to allow the creation of arrays which are not
  * NumPy arrays. If an array-like passed in as ``like`` supports
  * the ``__array_function__`` protocol, the result will be definedby it. In this case, it ensures the creation of an array object compatible with that passed in via this argument.

Returns
* out : ndarray
    * Array of zeros with the given shape, dtype, and order.



In [39]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
np.zeros((4,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [57]:
a = np.zeros_like()

##Zeros like
zeros_like : Return an array of zeros with shape and type of input.
empty : Return a new uninitialized array.
ones : Return a new array setting values to one.
full : Return a new array of given shape filled with value.

In [59]:
a = [22,12,34,34]
np.zeros_like(a)

array([0, 0, 0, 0])

In [61]:
lst = [
        [1,2,3],
        [4,5.1,6],
        [7,8,9]
       ]

np.zeros_like(lst)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [62]:
lst = [
        [1,2,3],
        [4,5.1,6],
        [7,8,9]
       ]

np.zeros_like(lst , dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])